#[derive(Debug)]
pub enum Error {
    Errno(u16),
    Kernel(u16),
    TaskLib(u16),
    DbgLib(u16),
    VxdbgLib(u16),
    DsmLib(u16),
    FioLib(u16),
    IoLib(u16),
    IosLib(u16),
    LoadLib(u16),
    LstLib(u16),
    MemLib(u16),
    RngLib(u16),
    SemLib(u16),
    VwModNum(u16),
    SymLib(u16),
    TyLib(u16),
    WdLib(u16),
    UsrLib(u16),
    RemLib(u16),
    NetDrv(u16),
    InetLib(u16),
    RouteLib(u16),
    NfsDrv(u16),
    NfsLib(u16),
    RpcClntStat(u16),
    NfsStat(u16),
    ErrnoLib(u16),
    HostLib(u16),
    SigLib(u16),
    FtnLib(u16),
    IfSl(u16),
    LoginLib(u16),
    ScsiLib(u16),
    DosFsLib(u16),
    SelectLib(u16),
    HashLib(u16),
    QLib(u16),
    TickLib(u16),
    ObjLib(u16),
    QPriHeapLib(u16),
    QPriBMapLib(u16),
    BufLib(u16),
    MsgQLib(u16),
    ClassLib(u16),
    IntLib(u16),
    DirLib(u16),
    CacheLib(u16),
    RawFsLib(u16),
    ArpLib(u16),
    SmLib(u16),
    BootpLib(u16),
    IcmpLib(u16),
    TftpLib(u16),
    ProxyArpLib(u16),
    SmUtilLib(u16),
    SmPktLib(u16),
    LoadEcoffLib(u16),
    LoadAoutLib(u16),
    LoadBoutLib(u16),
    BootLoadLib(u16),
    LoadCoffLib(u16),
    VmLib(u16),
    MmuLib(u16),
    ModuleLib(u16),
    UnldLib(u16),
    SmObjLib(u16),
    SmNameLib(u16),
    CplusLib(u16),
    M2Lib(u16),
    AioPxLib(u16),
    LoadAoutHppaLib(u16),
    MountLib(u16),
    NfsdLib(u16),
    LoadSomCoffLib(u16),
    LoadElfLib(u16),
    MbufLib(u16),
    PingLib(u16),
    StrmLib(u16),
    PppSecretLib(u16),
    PppHookLib(u16),
    TapeFsLib(u16),
    SnmpdLib(u16),
    PcmciaLib(u16),
    DhcpcLib(u16),
    ResolvLib(u16),
    EndLib(u16),
    MuxLib(u16),
    M2RipLib(u16),
    OspfLib(u16),
    DhcpsLib(u16),
    SntpcLib(u16),
    SntpsLib(u16),
    NetBufLib(u16),
    CdromFsLib(u16),
    LoadPecoffLib(u16),
    DistLib(u16),
    DistNameLib(u16),
    MsgQDistGrpLib(u16),
    MsgQDistLib(u16),
    IfUl(u16),
    MiiLib(u16),
    PoolLib(u16),
    SetLib(u16),
    DmsLib(u16),
    RarpLib(u16),
    IgmpRouterLib(u16),
    DevCfgLib(u16),
    QPriMaskLib(u16),
    UsbHostLib(u16),
    UsbPeriphLib(u16),
    CbioLib(u16),
    EventLib(u16),
    FastPathLib(u16),
    FtpLib(u16),
    FastUdpLib(u16),
    EdrLib(u16),
    PmLib(u16),
    MemLogLib(u16),
    IpRouteLib(u16),
    Nfs3Stat(u16),
    AlarmLib(u16),
    AmsLib(u16),
    FmsLib(u16),
    HsiLib(u16),
    HsmsLib(u16),
    OmsLib(u16),
    RpmLib(u16),
    UmsLib(u16),
    CmsLib(u16),
    MmsLib(u16),
    PspLib(u16),
    XcomLib(u16),
    IpsLib(u16),
    RdsLib(u16),
    GrmLib(u16),
    MtpLib(u16),
    ExEngLib(u16),
    TplLib(u16),
    SmmLib(u16),
    GraLib(u16),
    ShellLib(u16),
    IsrLib(u16),
    RtpLib(u16),
    CoprocLib(u16),
    AdrSpaceLib(u16),
    PgPoolLib(u16),
    PgPoolPhysLib(u16),
    PgPoolVirtLib(u16),
    SyscallLib(u16),
    PgMgrLib(u16),
    LoadRtpLib(u16),
    HookLib(u16),
    UnLib(u16),
    SalLib(u16),
    SdLib(u16),
    ShlLib(u16),
    TlsLib(u16),
    LoadFileLib(u16),
    ExcLib(u16),
    HrfsLib(u16),
    ErfLib(u16),
    CoreDumpLib(u16),
    TaskPxLib(u16),
    Ipcom(u16),
    Dshm(u16),
    SpinLockLib(u16),
    VxCpuLib(u16),
    TffsLib(u16),
    DevMemLib(u16),
    PwrPolicyLib(u16),
    FtlLib(u16),
    CondVarLib(u16),
    UdbMgr(u16),
    UserIdentLib(u16),
    Hypervisor(u16),
    PrivilegesLib(u16),
    RtpPart(u16),
    PppLib(u16),
    SshLib(u16),
    MsgQGblLib(u16),
    ApexObjLib(u16),
    PartitionLib(u16),
    HmLib(u16),
    PayloadLib(u16),
    ConfigRecordLib(u16),
    SslLib(u16),
    Vxcontainer(u16),
    VxcMgrLib(u16),

    Unknown(u16),
}

impl From<i32> for Error {
    fn from(x: i32) -> Self {
        let lib: u16 = (x >> 16) as u16;
        let err: u16 = (x & 0xFFFF) as u16;
        match lib {
            0 => Self::Errno(err.into()), /* THIS MUST BE ZERO! */
            1 => Self::Kernel(err.into()),
            3 => Self::TaskLib(err.into()),
            4 => Self::DbgLib(err.into()),
            5 => Self::VxdbgLib(err.into()),
            7 => Self::DsmLib(err.into()),
            9 => Self::FioLib(err.into()),
            12 => Self::IoLib(err.into()),
            13 => Self::IosLib(err.into()),
            14 => Self::LoadLib(err.into()),
            15 => Self::LstLib(err.into()),
            17 => Self::MemLib(err.into()),
            19 => Self::RngLib(err.into()),
            22 => Self::SemLib(err.into()),
            27 => Self::VwModNum(err.into()),
            28 => Self::SymLib(err.into()),
            31 => Self::TyLib(err.into()),
            34 => Self::WdLib(err.into()),
            35 => Self::UsrLib(err.into()),
            37 => Self::RemLib(err.into()),
            41 => Self::NetDrv(err.into()),
            43 => Self::InetLib(err.into()),
            44 => Self::RouteLib(err.into()),
            45 => Self::NfsDrv(err.into()),
            46 => Self::NfsLib(err.into()),
            47 => Self::RpcClntStat(err.into()),
            48 => Self::NfsStat(err.into()),
            49 => Self::ErrnoLib(err.into()),
            50 => Self::HostLib(err.into()),
            51 => Self::SigLib(err.into()),
            52 => Self::FtnLib(err.into()),
            53 => Self::IfSl(err.into()),
            54 => Self::LoginLib(err.into()),
            55 => Self::ScsiLib(err.into()),
            56 => Self::DosFsLib(err.into()),
            57 => Self::SelectLib(err.into()),
            58 => Self::HashLib(err.into()),
            59 => Self::QLib(err.into()),
            60 => Self::TickLib(err.into()),
            61 => Self::ObjLib(err.into()),
            62 => Self::QPriHeapLib(err.into()),
            63 => Self::QPriBMapLib(err.into()),
            64 => Self::BufLib(err.into()),
            65 => Self::MsgQLib(err.into()),
            66 => Self::ClassLib(err.into()),
            67 => Self::IntLib(err.into()),
            68 => Self::DirLib(err.into()),
            69 => Self::CacheLib(err.into()),
            70 => Self::RawFsLib(err.into()),
            71 => Self::ArpLib(err.into()),
            72 => Self::SmLib(err.into()),
            73 => Self::BootpLib(err.into()),
            74 => Self::IcmpLib(err.into()),
            75 => Self::TftpLib(err.into()),
            76 => Self::ProxyArpLib(err.into()),
            77 => Self::SmUtilLib(err.into()),
            78 => Self::SmPktLib(err.into()),
            79 => Self::LoadEcoffLib(err.into()),
            80 => Self::LoadAoutLib(err.into()),
            81 => Self::LoadBoutLib(err.into()),
            82 => Self::BootLoadLib(err.into()),
            83 => Self::LoadCoffLib(err.into()),
            84 => Self::VmLib(err.into()),
            85 => Self::MmuLib(err.into()),
            86 => Self::ModuleLib(err.into()),
            87 => Self::UnldLib(err.into()),
            88 => Self::SmObjLib(err.into()),
            89 => Self::SmNameLib(err.into()),
            90 => Self::CplusLib(err.into()),
            91 => Self::M2Lib(err.into()),
            92 => Self::AioPxLib(err.into()),
            93 => Self::LoadAoutHppaLib(err.into()),
            94 => Self::MountLib(err.into()),
            95 => Self::NfsdLib(err.into()),
            96 => Self::LoadSomCoffLib(err.into()),
            97 => Self::LoadElfLib(err.into()),
            98 => Self::MbufLib(err.into()),
            99 => Self::PingLib(err.into()),
            100 => Self::StrmLib(err.into()),
            101 => Self::PppSecretLib(err.into()),
            102 => Self::PppHookLib(err.into()),
            103 => Self::TapeFsLib(err.into()),
            104 => Self::SnmpdLib(err.into()),
            105 => Self::PcmciaLib(err.into()),
            106 => Self::DhcpcLib(err.into()),
            107 => Self::ResolvLib(err.into()),
            108 => Self::EndLib(err.into()),
            109 => Self::MuxLib(err.into()),
            110 => Self::M2RipLib(err.into()),
            111 => Self::OspfLib(err.into()),
            112 => Self::DhcpsLib(err.into()),
            113 => Self::SntpcLib(err.into()),
            114 => Self::SntpsLib(err.into()),
            115 => Self::NetBufLib(err.into()),
            116 => Self::CdromFsLib(err.into()),
            117 => Self::LoadPecoffLib(err.into()),
            118 => Self::DistLib(err.into()),
            119 => Self::DistNameLib(err.into()),
            120 => Self::MsgQDistGrpLib(err.into()),
            121 => Self::MsgQDistLib(err.into()),
            122 => Self::IfUl(err.into()),
            123 => Self::MiiLib(err.into()),
            124 => Self::PoolLib(err.into()),
            125 => Self::SetLib(err.into()),
            126 => Self::DmsLib(err.into()),
            127 => Self::RarpLib(err.into()),
            128 => Self::IgmpRouterLib(err.into()),
            129 => Self::DevCfgLib(err.into()),
            130 => Self::QPriMaskLib(err.into()),
            131 => Self::UsbHostLib(err.into()),
            132 => Self::UsbPeriphLib(err.into()),
            133 => Self::CbioLib(err.into()),
            134 => Self::EventLib(err.into()),
            135 => Self::FastPathLib(err.into()),
            136 => Self::FtpLib(err.into()),
            137 => Self::FastUdpLib(err.into()),
            138 => Self::EdrLib(err.into()),
            139 => Self::PmLib(err.into()),
            140 => Self::MemLogLib(err.into()),
            141 => Self::IpRouteLib(err.into()),
            142 => Self::Nfs3Stat(err.into()),
            153 => Self::AlarmLib(err.into()),
            154 => Self::AmsLib(err.into()),
            155 => Self::FmsLib(err.into()),
            156 => Self::HsiLib(err.into()),
            157 => Self::HsmsLib(err.into()),
            158 => Self::OmsLib(err.into()),
            159 => Self::RpmLib(err.into()),
            160 => Self::UmsLib(err.into()),
            161 => Self::CmsLib(err.into()),
            162 => Self::MmsLib(err.into()),
            163 => Self::PspLib(err.into()),
            164 => Self::XcomLib(err.into()),
            165 => Self::IpsLib(err.into()),
            166 => Self::RdsLib(err.into()),
            167 => Self::GrmLib(err.into()),
            168 => Self::MtpLib(err.into()),
            169 => Self::ExEngLib(err.into()),
            170 => Self::TplLib(err.into()),
            171 => Self::SmmLib(err.into()),
            172 => Self::GraLib(err.into()),
            173 => Self::ShellLib(err.into()),
            175 => Self::IsrLib(err.into()),
            178 => Self::RtpLib(err.into()),
            179 => Self::CoprocLib(err.into()),
            180 => Self::AdrSpaceLib(err.into()),
            181 => Self::PgPoolLib(err.into()),
            182 => Self::PgPoolPhysLib(err.into()),
            183 => Self::PgPoolVirtLib(err.into()),
            184 => Self::SyscallLib(err.into()),
            185 => Self::PgMgrLib(err.into()),
            186 => Self::LoadRtpLib(err.into()),
            187 => Self::HookLib(err.into()),
            188 => Self::UnLib(err.into()),
            189 => Self::SalLib(err.into()),
            190 => Self::SdLib(err.into()),
            191 => Self::ShlLib(err.into()),
            192 => Self::TlsLib(err.into()),
            193 => Self::LoadFileLib(err.into()),
            194 => Self::ExcLib(err.into()),
            195 => Self::HrfsLib(err.into()),
            196 => Self::ErfLib(err.into()),
            197 => Self::CoreDumpLib(err.into()),
            198 => Self::TaskPxLib(err.into()),
            199 => Self::Ipcom(err.into()),
            200 => Self::Dshm(err.into()),
            201 => Self::SpinLockLib(err.into()),
            202 => Self::VxCpuLib(err.into()),
            203 => Self::TffsLib(err.into()),
            204 => Self::DevMemLib(err.into()),
            205 => Self::PwrPolicyLib(err.into()),
            206 => Self::FtlLib(err.into()),
            207 => Self::CondVarLib(err.into()),
            208 => Self::UdbMgr(err.into()),
            209 => Self::UserIdentLib(err.into()),
            210 => Self::Hypervisor(err.into()),
            211 => Self::PrivilegesLib(err.into()),
            212 => Self::RtpPart(err.into()),
            213 => Self::PppLib(err.into()),
            214 => Self::SshLib(err.into()),
            216 => Self::MsgQGblLib(err.into()),
            217 => Self::ApexObjLib(err.into()),
            218 => Self::PartitionLib(err.into()),
            219 => Self::HmLib(err.into()),
            220 => Self::PayloadLib(err.into()),
            221 => Self::ConfigRecordLib(err.into()),
            222 => Self::SslLib(err.into()),
            223 => Self::Vxcontainer(err.into()),
            224 => Self::VxcMgrLib(err.into()),
            _ => Self::Unknown(err.into()),
        }
    }
}

pub enum ObjLibError {
    IdError,
    Unavailable,
    Deleted,
    Timeout,
    NoMethod,
    NoAccessRights,
    NameTruncated,
    NameClash,
    NotNamed,
    IllegalClassType,
    OperationUnsupported,
    InvalidOwner,
    RenameNotAllowed,
    DestroyError,
    HandleTblFull,
    NotFound,
    InvalidArgument,
    LibNotInitialized,
    AccessDenied,
    Unknown(u16),
}

impl From<u16> for ObjLibError {
    fn from(value: u16) -> Self {
        match value {
            0x01 => ObjLibError::IdError,
            0x02 => ObjLibError::Unavailable,
            0x03 => ObjLibError::Deleted,
            0x04 => ObjLibError::Timeout,
            0x05 => ObjLibError::NoMethod,
            0x06 => ObjLibError::NoAccessRights,
            0x07 => ObjLibError::NameTruncated,
            0x08 => ObjLibError::NameClash,
            0x09 => ObjLibError::NotNamed,
            0x0A => ObjLibError::IllegalClassType,
            0x0B => ObjLibError::OperationUnsupported,
            0x0C => ObjLibError::InvalidOwner,
            0x0D => ObjLibError::RenameNotAllowed,
            0x0E => ObjLibError::DestroyError,
            0x0F => ObjLibError::HandleTblFull,
            0x10 => ObjLibError::NotFound,
            0x11 => ObjLibError::InvalidArgument,
            0x12 => ObjLibError::LibNotInitialized,
            0x13 => ObjLibError::AccessDenied,
            _ => Self::Unknown(value),
        }
    }
}
